"""implement_identity_separation_schema

Revision ID: 4a2fbae74927
Revises: d1ab1537da5c
Create Date: 2026-05-10 22:03:03.303309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a2fbae74927'
down_revision: Union[str, None] = 'd1ab1537da5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_identities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_identities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_identities')),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_user_identities_provider')
    )
    op.create_index('ix_user_identities_user_id', 'user_identities', ['user_id'], unique=False)
    
    # Data migration: Move existing auth data from users to user_identities
    op.execute("""
        INSERT INTO user_identities (id, user_id, provider, provider_user_id, password_hash, created_at, last_used_at)
        SELECT gen_random_uuid(), id, auth_provider, COALESCE(google_id, email), password_hash, created_at, updated_at
        FROM users
    """)

    op.drop_table('seed_registry')
    op.drop_constraint(op.f('uq_users_google_id'), 'users', type_='unique')
    op.drop_column('users', 'google_id')
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('auth_provider', sa.VARCHAR(length=20), server_default=sa.text("'local'::character varying"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('google_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('uq_users_google_id'), 'users', ['google_id'], postgresql_nulls_not_distinct=False)
    op.create_table('seed_registry',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('checksum', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('seeded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('seed_registry_pkey'))
    )
    op.drop_index('ix_user_identities_user_id', table_name='user_identities')
    op.drop_table('user_identities')
    # ### end Alembic commands ###
